version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000    
    ports:
      - "6000:80"
    volumes:
      - .:/code
    depends_on:
      - data
  data:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'alifarhadi'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password123'
      MYSQL_ROOT_PASSWORD: 'password123'
    ports:
      - '3309:3306'


