# Generated by Django 5.0.1 on 2024-01-08 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_django.courses')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_django.teacher')),
            ],
        ),
    ]
